### ISSUE TITLE
Time inconsistencies

### ISSUE THREAD

**Issue by Speiger** [lwjglgamedev/vulkanbook#58]
o/
Started reading the book.
Which by the way i assume the book isn't hosted on github yet (because the link is just going to the github page instead of the fancy book page) since the book ins't finished yet.

But i noticed one inconsistent factor.
https://github.com/lwjglgamedev/vulkanbook/blob/fb38abd56650ece169a5da11635a7644a5d2e76f/bookcontents/chapter-01/chapter-01.md?plain=1#L112

Now and updateTime are both in Milliseconds, yet you define it in "Nanoseconds". What is it now?
Nano or Milli?

**Comment by lwjglgamedev** [comment]
Hi,

I'm not sure of understanding your first part. The book is hosted in github and it is finished (well nothing is never finished but you can consider it as complete). It is not hosted in gitbook though (mainly because you can have only one book for free, therefore it will be in github.

Regarding your scond part, it is a typo it should be millis. In the first versions I used nanoseconds but changed it to millis and fogot to correct the name. Thanks for reporting this. I will fix this now.

**Comment by Speiger** [comment]
> I'm not sure of understanding your first part. The book is hosted in github and it is finished (well nothing is never finished but you can consider it as complete). It is not hosted in gitbook though (mainly because you can have only one book for free, therefore it will be in github.

Well on the "readme.md" and this is the text.
The book itself is also hosted in [GitHub](https://github.com/lwjglgamedev/vulkanbook/tree/master/bookcontents).
Please try clicking it.
In other words there is no way from the repo to come to the book itself, while in the other books there is always a link to the book itself.

**Comment by lwjglgamedev** [comment]
The repo is the book. In the OpenGL version, the book is hosted in Gitbook. Since it is not possible to have two books (for free) it is hosted in Github as a repository. The repo is the book and the book is the repo.

**Comment by Speiger** [comment]
Ahhhh ok, that explains it :)
Ok thank you for the explanation!
One thing I would ask, please give the chapters some names outside of the "chapters" this is the one thing i am missing for the vulkan book.
Maybe use the wiki as a chapter index?
